WARN  2018-04-20 09:20:46,354 (StunServiceImpl.java:420) received no response from STUN server stunserver.org/67.227.226.240:3478 at local address /10.170.41.138:0
ERROR 2018-04-20 09:20:57,399 (XMPPConnectionService.java:400)  new connection state == ERROR
gmail.com:5222 Exception: XMPPError connecting to gmail.com:5222.; : remote-server-error(502)
  -- caused by: XMPPError connecting to gmail.com:5222.: remote-server-error(502) XMPPError connecting to gmail.com:5222.
  -- caused by: java.net.ConnectException: Connection timed out: connect
	at org.jivesoftware.smack.XMPPConnection.connectUsingConfiguration(XMPPConnection.java:592)
	at org.jivesoftware.smack.XMPPConnection.connect(XMPPConnection.java:1010)
	at de.fu_berlin.inf.dpp.net.xmpp.XMPPConnectionService.connect(XMPPConnectionService.java:268)
	at de.fu_berlin.inf.dpp.communication.connection.ConnectionHandler.connectXMPPInternal(ConnectionHandler.java:332)
	at de.fu_berlin.inf.dpp.communication.connection.ConnectionHandler.connect(ConnectionHandler.java:190)
	at de.fu_berlin.inf.dpp.StartupSaros$1.run(StartupSaros.java:113)
	at de.fu_berlin.inf.dpp.util.ThreadUtils$1.run(ThreadUtils.java:38)
	at java.lang.Thread.run(Unknown Source)
Nested Exception: 
XMPPError connecting to gmail.com:5222.: remote-server-error(502) XMPPError connecting to gmail.com:5222.
  -- caused by: java.net.ConnectException: Connection timed out: connect
	at org.jivesoftware.smack.XMPPConnection.connectUsingConfiguration(XMPPConnection.java:565)
	at org.jivesoftware.smack.XMPPConnection.connect(XMPPConnection.java:1010)
	at de.fu_berlin.inf.dpp.net.xmpp.XMPPConnectionService.connect(XMPPConnectionService.java:268)
	at de.fu_berlin.inf.dpp.communication.connection.ConnectionHandler.connectXMPPInternal(ConnectionHandler.java:332)
	at de.fu_berlin.inf.dpp.communication.connection.ConnectionHandler.connect(ConnectionHandler.java:190)
	at de.fu_berlin.inf.dpp.StartupSaros$1.run(StartupSaros.java:113)
	at de.fu_berlin.inf.dpp.util.ThreadUtils$1.run(ThreadUtils.java:38)
	at java.lang.Thread.run(Unknown Source)
Nested Exception: 
java.net.ConnectException: Connection timed out: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at org.jivesoftware.smack.proxy.DirectSocketFactory.createSocket(DirectSocketFactory.java:45)
	at org.jivesoftware.smack.XMPPConnection.connectUsingConfiguration(XMPPConnection.java:557)
	at org.jivesoftware.smack.XMPPConnection.connect(XMPPConnection.java:1010)
	at de.fu_berlin.inf.dpp.net.xmpp.XMPPConnectionService.connect(XMPPConnectionService.java:268)
	at de.fu_berlin.inf.dpp.communication.connection.ConnectionHandler.connectXMPPInternal(ConnectionHandler.java:332)
	at de.fu_berlin.inf.dpp.communication.connection.ConnectionHandler.connect(ConnectionHandler.java:190)
	at de.fu_berlin.inf.dpp.StartupSaros$1.run(StartupSaros.java:113)
	at de.fu_berlin.inf.dpp.util.ThreadUtils$1.run(ThreadUtils.java:38)
	at java.lang.Thread.run(Unknown Source)
ERROR 2018-04-20 09:22:15,971 (StunServiceImpl.java:155) an error occurred while performing a STUN discovery: ICMP Port Unreachable
java.net.PortUnreachableException: ICMP Port Unreachable
	at java.net.DualStackPlainDatagramSocketImpl.socketReceiveOrPeekData(Native Method)
	at java.net.DualStackPlainDatagramSocketImpl.receive0(Unknown Source)
	at java.net.AbstractPlainDatagramSocketImpl.receive(Unknown Source)
	at java.net.DatagramSocket.receive(Unknown Source)
	at de.fu_berlin.inf.dpp.net.stun.internal.StunServiceImpl$StunDiscovery.performStunDiscovery(StunServiceImpl.java:284)
	at de.fu_berlin.inf.dpp.net.stun.internal.StunServiceImpl$StunDiscovery.run(StunServiceImpl.java:151)
	at java.lang.Thread.run(Unknown Source)
WARN  2018-04-20 09:22:25,373 (Socks5Transport.java:324) [SOCKS5Transport] Received response connection without a running connect
WARN  2018-04-20 09:22:39,625 (DiscoveryManager.java:451) Service Discovery failed on recipient 0wujn3hst7h5y3dghnm6q0lj9t@public.talk.google.com/MessagingB1445C87900 server: xmpp.l.google.com
No response from the server.: 
	at org.jivesoftware.smackx.ServiceDiscoveryManager.discoverInfo(ServiceDiscoveryManager.java:534)
	at org.jivesoftware.smackx.ServiceDiscoveryManager.discoverInfo(ServiceDiscoveryManager.java:489)
	at de.fu_berlin.inf.dpp.net.xmpp.discovery.DiscoveryManager.performServiceDiscovery(DiscoveryManager.java:448)
	at de.fu_berlin.inf.dpp.net.xmpp.discovery.DiscoveryManager.queryFeatureSupport(DiscoveryManager.java:380)
	at de.fu_berlin.inf.dpp.net.xmpp.discovery.DiscoveryManager.access$3(DiscoveryManager.java:347)
	at de.fu_berlin.inf.dpp.net.xmpp.discovery.DiscoveryManager$2.run(DiscoveryManager.java:326)
	at de.fu_berlin.inf.dpp.util.ThreadUtils$1.run(ThreadUtils.java:38)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
WARN  2018-04-20 09:23:09,721 (DiscoveryManager.java:451) Service Discovery failed on recipient 0wujn3hst7h5y3dghnm6q0lj9t@public.talk.google.com/MessagingB1445C87900 server: xmpp.l.google.com
No response from the server.: 
	at org.jivesoftware.smackx.ServiceDiscoveryManager.discoverInfo(ServiceDiscoveryManager.java:534)
	at org.jivesoftware.smackx.ServiceDiscoveryManager.discoverInfo(ServiceDiscoveryManager.java:489)
	at de.fu_berlin.inf.dpp.net.xmpp.discovery.DiscoveryManager.performServiceDiscovery(DiscoveryManager.java:448)
	at de.fu_berlin.inf.dpp.net.xmpp.discovery.DiscoveryManager.queryFeatureSupport(DiscoveryManager.java:380)
	at de.fu_berlin.inf.dpp.net.xmpp.discovery.DiscoveryManager.access$3(DiscoveryManager.java:347)
	at de.fu_berlin.inf.dpp.net.xmpp.discovery.DiscoveryManager$2.run(DiscoveryManager.java:326)
	at de.fu_berlin.inf.dpp.util.ThreadUtils$1.run(ThreadUtils.java:38)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
ERROR 2018-04-20 09:23:24,350 (MultiUserChatService.java:114) Couldn't join chat: SAROS_1720758143@conference.funk.cs.fcps.org
No response from server.: 
	at org.jivesoftware.smackx.muc.MultiUserChat.create(MultiUserChat.java:367)
	at de.fu_berlin.inf.dpp.communication.chat.muc.MultiUserChat.createAndJoinMUC(MultiUserChat.java:266)
	at de.fu_berlin.inf.dpp.communication.chat.muc.MultiUserChat.connect(MultiUserChat.java:177)
	at de.fu_berlin.inf.dpp.communication.chat.muc.MultiUserChatService.createChat(MultiUserChatService.java:111)
	at de.fu_berlin.inf.dpp.ui.widgets.chat.ChatRoomsComposite.createChat(ChatRoomsComposite.java:670)
	at de.fu_berlin.inf.dpp.ui.widgets.chat.ChatRoomsComposite.access$4(ChatRoomsComposite.java:665)
	at de.fu_berlin.inf.dpp.ui.widgets.chat.ChatRoomsComposite$5$2.run(ChatRoomsComposite.java:255)
	at de.fu_berlin.inf.dpp.util.ThreadUtils$1.run(ThreadUtils.java:38)
	at java.lang.Thread.run(Unknown Source)
ERROR 2018-04-20 09:53:03,624 (ActivitySequencer.java:504) failed to sent activities: [TextSelectionActivity(offset: 3694, length: 0, src: bluetangkid@gmail.com/Saros97D02A81, path: SPath [path=src/game/Game.java, project=gameEngine])]
java.io.IOException: not connected to exec.nathan@gmail.com/SarosA9123AFB [connection identifier=saros-main-session]
	at de.fu_berlin.inf.dpp.net.internal.DataTransferManager.sendData(DataTransferManager.java:206)
	at de.fu_berlin.inf.dpp.net.internal.XMPPTransmitter.send(XMPPTransmitter.java:90)
	at de.fu_berlin.inf.dpp.project.internal.ActivitySequencer.sendActivities(ActivitySequencer.java:501)
	at de.fu_berlin.inf.dpp.project.internal.ActivitySequencer.access$3(ActivitySequencer.java:482)
	at de.fu_berlin.inf.dpp.project.internal.ActivitySequencer$2.run(ActivitySequencer.java:152)
	at de.fu_berlin.inf.dpp.util.ThreadUtils$1.run(ThreadUtils.java:38)
	at java.lang.Thread.run(Unknown Source)
WARN  2018-04-20 09:53:03,653 (SarosSession.java:655) failed to notify user exec.nathan@gmail.com/SarosA9123AFB about local session stop
java.io.IOException: not connected to exec.nathan@gmail.com/SarosA9123AFB [connection identifier=saros-main-session]
	at de.fu_berlin.inf.dpp.net.internal.DataTransferManager.sendData(DataTransferManager.java:206)
	at de.fu_berlin.inf.dpp.net.internal.XMPPTransmitter.send(XMPPTransmitter.java:90)
	at de.fu_berlin.inf.dpp.project.internal.SarosSession.stop(SarosSession.java:651)
	at de.fu_berlin.inf.dpp.project.SarosSessionManager.stopSarosSession(SarosSessionManager.java:340)
	at de.fu_berlin.inf.dpp.project.internal.timeout.SessionTimeoutHandler$3.run(SessionTimeoutHandler.java:115)
	at de.fu_berlin.inf.dpp.util.ThreadUtils$1.run(ThreadUtils.java:38)
	at java.lang.Thread.run(Unknown Source)
WARN  2018-04-20 09:53:33,671 (DiscoveryManager.java:451) Service Discovery failed on recipient 0wujn3hst7h5y3dghnm6q0lj9t@public.talk.google.com/MessagingB1445C87900 server: xmpp.l.google.com
No response from the server.: 
	at org.jivesoftware.smackx.ServiceDiscoveryManager.discoverInfo(ServiceDiscoveryManager.java:534)
	at org.jivesoftware.smackx.ServiceDiscoveryManager.discoverInfo(ServiceDiscoveryManager.java:489)
	at de.fu_berlin.inf.dpp.net.xmpp.discovery.DiscoveryManager.performServiceDiscovery(DiscoveryManager.java:448)
	at de.fu_berlin.inf.dpp.net.xmpp.discovery.DiscoveryManager.queryFeatureSupport(DiscoveryManager.java:380)
	at de.fu_berlin.inf.dpp.net.xmpp.discovery.DiscoveryManager.access$3(DiscoveryManager.java:347)
	at de.fu_berlin.inf.dpp.net.xmpp.discovery.DiscoveryManager$2.run(DiscoveryManager.java:326)
	at de.fu_berlin.inf.dpp.util.ThreadUtils$1.run(ThreadUtils.java:38)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
ERROR 2018-04-20 09:53:51,379 (XMPPUtils.java:345) discovery for service 'gmail.com' failed
feature-not-implemented(501)
	at org.jivesoftware.smackx.ServiceDiscoveryManager.discoverItems(ServiceDiscoveryManager.java:587)
	at org.jivesoftware.smackx.ServiceDiscoveryManager.discoverItems(ServiceDiscoveryManager.java:550)
	at de.fu_berlin.inf.dpp.net.util.XMPPUtils.getMultiUserChatService(XMPPUtils.java:343)
	at de.fu_berlin.inf.dpp.communication.chat.muc.negotiation.MUCNegotiationManager.getMUCService(MUCNegotiationManager.java:168)
	at de.fu_berlin.inf.dpp.communication.chat.muc.negotiation.MUCNegotiationManager.getOwnPreferences(MUCNegotiationManager.java:125)
	at de.fu_berlin.inf.dpp.ui.widgets.chat.ChatRoomsComposite.createChat(ChatRoomsComposite.java:667)
	at de.fu_berlin.inf.dpp.ui.widgets.chat.ChatRoomsComposite.access$4(ChatRoomsComposite.java:665)
	at de.fu_berlin.inf.dpp.ui.widgets.chat.ChatRoomsComposite$5$2.run(ChatRoomsComposite.java:255)
	at de.fu_berlin.inf.dpp.util.ThreadUtils$1.run(ThreadUtils.java:38)
	at java.lang.Thread.run(Unknown Source)
WARN  2018-04-20 09:53:51,385 (MultiUserChatService.java:103) MUC service is not available, aborting connection request
ERROR 2018-04-20 09:54:01,437 (OutgoingSessionNegotiation.java:262) OSN [remote side: exec.nathan@gmail.com/SarosA9123AFB] : could not obtain remote Saros version
ERROR 2018-04-20 09:54:01,447 (CancelableProcess.java:398) cancelled process OSN [remote side: exec.nathan@gmail.com/SarosA9123AFB], error: Could not obtain the version of the Saros plugin from exec.nathan@gmail.com. Please try again.
ERROR 2018-04-20 09:54:20,816 (XMPPUtils.java:345) discovery for service 'gmail.com' failed
feature-not-implemented(501)
	at org.jivesoftware.smackx.ServiceDiscoveryManager.discoverItems(ServiceDiscoveryManager.java:587)
	at org.jivesoftware.smackx.ServiceDiscoveryManager.discoverItems(ServiceDiscoveryManager.java:550)
	at de.fu_berlin.inf.dpp.net.util.XMPPUtils.getMultiUserChatService(XMPPUtils.java:343)
	at de.fu_berlin.inf.dpp.communication.chat.muc.negotiation.MUCNegotiationManager.getMUCService(MUCNegotiationManager.java:168)
	at de.fu_berlin.inf.dpp.communication.chat.muc.negotiation.MUCNegotiationManager.getOwnPreferences(MUCNegotiationManager.java:125)
	at de.fu_berlin.inf.dpp.ui.widgets.chat.ChatRoomsComposite.createChat(ChatRoomsComposite.java:667)
	at de.fu_berlin.inf.dpp.ui.widgets.chat.ChatRoomsComposite.access$4(ChatRoomsComposite.java:665)
	at de.fu_berlin.inf.dpp.ui.widgets.chat.ChatRoomsComposite$5$2.run(ChatRoomsComposite.java:255)
	at de.fu_berlin.inf.dpp.util.ThreadUtils$1.run(ThreadUtils.java:38)
	at java.lang.Thread.run(Unknown Source)
WARN  2018-04-20 09:54:20,822 (MultiUserChatService.java:103) MUC service is not available, aborting connection request
WARN  2018-04-20 09:54:21,342 (DiscoveryManager.java:451) Service Discovery failed on recipient 0wujn3hst7h5y3dghnm6q0lj9t@public.talk.google.com/MessagingB1445C87900 server: xmpp.l.google.com
No response from the server.: 
	at org.jivesoftware.smackx.ServiceDiscoveryManager.discoverInfo(ServiceDiscoveryManager.java:534)
	at org.jivesoftware.smackx.ServiceDiscoveryManager.discoverInfo(ServiceDiscoveryManager.java:489)
	at de.fu_berlin.inf.dpp.net.xmpp.discovery.DiscoveryManager.performServiceDiscovery(DiscoveryManager.java:448)
	at de.fu_berlin.inf.dpp.net.xmpp.discovery.DiscoveryManager.queryFeatureSupport(DiscoveryManager.java:380)
	at de.fu_berlin.inf.dpp.net.xmpp.discovery.DiscoveryManager.access$3(DiscoveryManager.java:347)
	at de.fu_berlin.inf.dpp.net.xmpp.discovery.DiscoveryManager$2.run(DiscoveryManager.java:326)
	at de.fu_berlin.inf.dpp.util.ThreadUtils$1.run(ThreadUtils.java:38)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
ERROR 2018-04-20 09:54:25,876 (XMPPUtils.java:345) discovery for service 'gmail.com' failed
feature-not-implemented(501)
	at org.jivesoftware.smackx.ServiceDiscoveryManager.discoverItems(ServiceDiscoveryManager.java:587)
	at org.jivesoftware.smackx.ServiceDiscoveryManager.discoverItems(ServiceDiscoveryManager.java:550)
	at de.fu_berlin.inf.dpp.net.util.XMPPUtils.getMultiUserChatService(XMPPUtils.java:343)
	at de.fu_berlin.inf.dpp.communication.chat.muc.negotiation.MUCNegotiationManager.getMUCService(MUCNegotiationManager.java:168)
	at de.fu_berlin.inf.dpp.communication.chat.muc.negotiation.MUCNegotiationManager.getOwnPreferences(MUCNegotiationManager.java:125)
	at de.fu_berlin.inf.dpp.communication.chat.muc.negotiation.MUCNegotiationManager$1.considerClientPreferences(MUCNegotiationManager.java:72)
	at de.fu_berlin.inf.dpp.negotiation.OutgoingSessionNegotiation.determineSessionParameters(OutgoingSessionNegotiation.java:397)
	at de.fu_berlin.inf.dpp.negotiation.OutgoingSessionNegotiation.start(OutgoingSessionNegotiation.java:191)
	at de.fu_berlin.inf.dpp.ui.eventhandler.NegotiationHandler$OutgoingInvitationJob.run(NegotiationHandler.java:86)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
WARN  2018-04-20 09:54:26,671 (Socks5Transport.java:324) [SOCKS5Transport] Received response connection without a running connect
WARN  2018-04-20 09:54:51,348 (DiscoveryManager.java:451) Service Discovery failed on recipient 0wujn3hst7h5y3dghnm6q0lj9t@public.talk.google.com/MessagingB1445C87900 server: xmpp.l.google.com
No response from the server.: 
	at org.jivesoftware.smackx.ServiceDiscoveryManager.discoverInfo(ServiceDiscoveryManager.java:534)
	at org.jivesoftware.smackx.ServiceDiscoveryManager.discoverInfo(ServiceDiscoveryManager.java:489)
	at de.fu_berlin.inf.dpp.net.xmpp.discovery.DiscoveryManager.performServiceDiscovery(DiscoveryManager.java:448)
	at de.fu_berlin.inf.dpp.net.xmpp.discovery.DiscoveryManager.queryFeatureSupport(DiscoveryManager.java:380)
	at de.fu_berlin.inf.dpp.net.xmpp.discovery.DiscoveryManager.access$3(DiscoveryManager.java:347)
	at de.fu_berlin.inf.dpp.net.xmpp.discovery.DiscoveryManager$2.run(DiscoveryManager.java:326)
	at de.fu_berlin.inf.dpp.util.ThreadUtils$1.run(ThreadUtils.java:38)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
WARN  2018-04-20 09:55:21,355 (DiscoveryManager.java:451) Service Discovery failed on recipient 0wujn3hst7h5y3dghnm6q0lj9t@public.talk.google.com/MessagingB1445C87900 server: xmpp.l.google.com
No response from the server.: 
	at org.jivesoftware.smackx.ServiceDiscoveryManager.discoverInfo(ServiceDiscoveryManager.java:534)
	at org.jivesoftware.smackx.ServiceDiscoveryManager.discoverInfo(ServiceDiscoveryManager.java:489)
	at de.fu_berlin.inf.dpp.net.xmpp.discovery.DiscoveryManager.performServiceDiscovery(DiscoveryManager.java:448)
	at de.fu_berlin.inf.dpp.net.xmpp.discovery.DiscoveryManager.queryFeatureSupport(DiscoveryManager.java:380)
	at de.fu_berlin.inf.dpp.net.xmpp.discovery.DiscoveryManager.access$3(DiscoveryManager.java:347)
	at de.fu_berlin.inf.dpp.net.xmpp.discovery.DiscoveryManager$2.run(DiscoveryManager.java:326)
	at de.fu_berlin.inf.dpp.util.ThreadUtils$1.run(ThreadUtils.java:38)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
ERROR 2018-04-20 10:12:54,870 (XMPPConnectionService.java:101) XMPP connection error: 
java.io.EOFException: no more data available - expected end tag </stream:stream> to close start tag <stream:stream> from line 1, parser stopped on END_TAG seen ...uetangkid@gmail.com/Saros97D02A81" id="6038e-187" type="result"/> ... @1:29443
	at org.xmlpull.mxp1.MXParser.fillBuf(MXParser.java:3035)
	at org.xmlpull.mxp1.MXParser.more(MXParser.java:3046)
	at org.xmlpull.mxp1.MXParser.nextImpl(MXParser.java:1384)
	at org.xmlpull.mxp1.MXParser.next(MXParser.java:1093)
	at org.jivesoftware.smack.PacketReader.parsePackets(PacketReader.java:312)
	at org.jivesoftware.smack.PacketReader.access$000(PacketReader.java:48)
	at org.jivesoftware.smack.PacketReader$1.run(PacketReader.java:76)
ERROR 2018-04-20 10:12:54,875 (XMPPConnectionService.java:400)  new connection state == ERROR
java.io.EOFException: no more data available - expected end tag </stream:stream> to close start tag <stream:stream> from line 1, parser stopped on END_TAG seen ...uetangkid@gmail.com/Saros97D02A81" id="6038e-187" type="result"/> ... @1:29443
	at org.xmlpull.mxp1.MXParser.fillBuf(MXParser.java:3035)
	at org.xmlpull.mxp1.MXParser.more(MXParser.java:3046)
	at org.xmlpull.mxp1.MXParser.nextImpl(MXParser.java:1384)
	at org.xmlpull.mxp1.MXParser.next(MXParser.java:1093)
	at org.jivesoftware.smack.PacketReader.parsePackets(PacketReader.java:312)
	at org.jivesoftware.smack.PacketReader.access$000(PacketReader.java:48)
	at org.jivesoftware.smack.PacketReader$1.run(PacketReader.java:76)
ERROR 2018-04-20 10:13:00,997 (ActivitySequencer.java:504) failed to sent activities: [ChecksumActivity(path: SPath [path=src/world/Terrain.java, project=gameEngine], hash: -394280930, length: 6258, jupiterTimestamp: [23,0]), ChecksumActivity(path: SPath [path=src/networking/Client.java, project=gameEngine], hash: 700433503, length: 4296, jupiterTimestamp: [0,0])]
java.io.IOException: not connected to a XMPP server
	at de.fu_berlin.inf.dpp.net.internal.DataTransferManager.sendData(DataTransferManager.java:200)
	at de.fu_berlin.inf.dpp.net.internal.XMPPTransmitter.send(XMPPTransmitter.java:90)
	at de.fu_berlin.inf.dpp.project.internal.ActivitySequencer.sendActivities(ActivitySequencer.java:501)
	at de.fu_berlin.inf.dpp.project.internal.ActivitySequencer.access$3(ActivitySequencer.java:482)
	at de.fu_berlin.inf.dpp.project.internal.ActivitySequencer$2.run(ActivitySequencer.java:152)
	at de.fu_berlin.inf.dpp.util.ThreadUtils$1.run(ThreadUtils.java:38)
	at java.lang.Thread.run(Unknown Source)
